<div class="menu-item with-sub">
	<div class="side-menu-icon faicon">
		<a href="<?= $this->getAdminUrlNoDomain('settings'); ?>"><i class="fa-solid fa-gear"></i></a>
	</div>
	<div class="side-menu-label">
		<a href="<?= $this->getAdminUrlNoDomain('settings'); ?>">Setings</a>
	</div>
</div>

	
<div class="menu-item sub-menu">
	<div class="side-menu-icon faicon">
		<a href="<?= $this->getAdminUrlNoDomain('settings'); ?>"><i class="fa-regular fa-circle"></i></a>
	</div>
	<div class="side-menu-label">
		<a href="<?= $this->getAdminUrlNoDomain('settings'); ?>">Setings</a>
	</div>
</div>