<script src="/public/sys/dist/js/require.js"></script>

<script>
	requirejs.config({
		baseUrl: '<?= $this->getPublicUrl() ?>',
		paths: {
			"jquery": '/brightit/otime/js/admin/jquery',
			"bootstrap": 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min'
		},
		shim: {
			"bootstrap": {
				deps: ["jquery"]
			}
		}
	});

	<?php
	// require([
	// 	'jquery', 
	// 	'bootstrap'
	// ], function($, bootstrap){
	// 	console.log('exampleModal');
	// 	$("button").on('click', function(){
			
	// 		console.log('exampleModal');
	// 		$('#exampleModal').modal('show');
	// 	});
	// });
	?>
</script>
