<div class="menu-header">
	<!-- <button type="button" class="close d-md-block d-lg-none">
		<span>×</span>
	</button> -->
	
	<div class="side-menu-icon menu-header-logo">
		<img src="<?= $this->getImageUrl([
			'vendor'=>'Opoink',
			'module'=>'Bmodule',
			'path' => '/images',
			'filename' => 'default-logo.png'
		]) ?>">
	</div>

	<div class="side-menu-label">
		<span class="fs-800">Opoink</span> Admin
	</div>
</div>
<div class="menu-body">
	<?= $this->getChildHtml(); ?>
</div>