<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="<?= $this->getPublicUrl('/dist/plugins/fontawesome-free/css/all.min.css') ?>">
<!-- Theme style -->
<link rel="stylesheet" href="<?= $this->getPublicUrl('/dist/css/adminlte.min.css') ?>">

<?php
    echo $this->getChildHtml();
?>